name: My first Github Actions
on: [push]
jobs:
    build-app: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install node_modules
              run: yarn
            - name: Build the project
              run: yarn build
            - name: Setup finished
              run: echo "First CI-CD run!" 

